#!/bin/bash

CONFIGURATION=Release

cd "$(dirname "$0")"/../build/Xcode
set -ex

rm -rf build/$CONFIGURATION
xcodebuild -configuration $CONFIGURATION -alltargets
openssl rand 1000000 -out build/$CONFIGURATION/random.data

cd build/$CONFIGURATION
mkdir -p Distribution

frmver="$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "OctoFeed.framework/Resources/Info.plist")"
appver="$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "TestApp.app/Contents/Info.plist")"

zip -r Distribution/OctoFeed-${frmver}.zip OctoFeed.framework
zip -r Distribution/TestApp-${appver}.zip TestApp.app
zip Distribution/testrand.zip random.data

echo Distribution directory: $(PWD)/Distribution