#!/bin/bash

CONFIGURATION=Release

cd "$(dirname "$0")"/../build/Xcode
set -ex

rm -rf build/$CONFIGURATION
xcodebuild -configuration $CONFIGURATION -alltargets
openssl rand 1000000 -out build/$CONFIGURATION/random.data

cd build/$CONFIGURATION
mkdir -p Distribution

frmver="$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "OctoFeed.framework/Resources/Info.plist")"

ditto -ck --keepParent OctoFeed.framework Distribution/OctoFeed-${frmver}.zip
ditto -ck --keepParent TestApp.app Distribution/TestApp-UsedForTesting-NoNeedToDownload.zip
zip Distribution/RandomData-UsedForTesting-NoNeedToDownload.zip random.data

echo Distribution directory: $(PWD)/Distribution
