#!/bin/bash

prettydoc=../../prettydoc/prettydoc
stylesheet=../../prettydoc/prettydoc-templ/html.css

cd "$(dirname "$0")"/../doc

cat ../inc/OctoFeed/{NSString+Version.h,NSTask+Relaunch.h,OctoError.h,OctoRelease.h,OctoFeed.h} >OctoFeed.h
cp $stylesheet .
$prettydoc --headerdoc-path=/usr/bin/headerdoc2html -t -f html -S html.css OctoFeed.h
#$prettydoc --headerdoc-path=/usr/bin/headerdoc2html -t -f asciidoc OctoFeed.h
#$prettydoc --headerdoc-path=/usr/bin/headerdoc2html -t -f man OctoFeed.h
#$prettydoc --headerdoc-path=/usr/bin/headerdoc2html -t -f markdown OctoFeed.h
rm OctoFeed.h
